name: ci

on:
  push:
    branches: [ main, integration-tests ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          image: kindest/node:v1.20.7
      - run: 'wget https://fluxcd.io/install.sh'
      - run: 'bash install.sh'
      - name: extension test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: 'npm test'





